# Generated by Django 5.0.2 on 2024-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
