# Generated by Django 5.0.2 on 2024-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_alter_notice_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='stripe_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
