# Generated by Django 5.0.2 on 2024-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0010_hostels_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
