# Generated by Django 5.0.2 on 2024-03-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0011_alter_rooms_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='current_occupancy',
            field=models.IntegerField(),
        ),
    ]
