# Generated by Django 5.0.2 on 2024-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0012_alter_rooms_current_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
