# Generated by Django 5.0.2 on 2024-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0013_alter_rooms_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notification_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
