# Generated by Django 5.0.2 on 2024-02-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_accommodations_room_accommodations_student_and_more'),
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.hostels'),
        ),
    ]
