# Generated by Django 5.0.2 on 2024-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_accommodations_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
