# Generated by Django 5.0.2 on 2024-02-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customuser_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='room',
            new_name='hostel',
        ),
    ]
