# Generated by Django 5.0.2 on 2024-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_complaints_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
