# Generated by Django 5.0.2 on 2024-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_accommodations_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
