# Generated by Django 5.0.2 on 2024-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_accommodations_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodations',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
