# Generated by Django 5.0.2 on 2024-02-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_accommodations_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months')], null=True),
        ),
    ]
