# Generated by Django 5.0.2 on 2024-02-20 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_accommodations_duration'),
        ('hostels', '0005_alter_rooms_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='status',
        ),
        migrations.AddField(
            model_name='payments',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.hostels'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='type',
            field=models.CharField(blank=True, choices=[('damages', 'Damages'), ('accommodation', 'Accommodation')], max_length=20, null=True),
        ),
    ]
