# Generated by Django 5.0.2 on 2024-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('NZD', 'New Zealand Dollar'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='payments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='credit_card', max_length=20),
        ),
    ]
