# Generated by Django 5.0.2 on 2024-03-09 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
