# Generated by Django 5.0.2 on 2024-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_accommodations_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
