# Generated by Django 5.0.2 on 2024-02-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_maintenance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='room_price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='room_price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='room_price_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
