# Generated by Django 5.0.2 on 2024-03-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_hostels_imag11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('maintenance', 'maintenance'), ('complaints', 'complaints'), ('payment', 'payment'), ('accomodation', 'accomodation'), ('account', 'account')], max_length=20, null=True),
        ),
    ]
