# Generated by Django 5.0.2 on 2024-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0014_alter_notice_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
