# Generated by Django 5.0.2 on 2024-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0015_hostels_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
